# Generated by Django 4.1.5 on 2023-02-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Admin"),
                    ("M", "Member"),
                    ("I", "Requested to join"),
                    ("O", "Received offer to join"),
                ],
                max_length=1,
            ),
        ),
    ]
